/**
 * @generated — do not edit manually.
 *
 * Generated by @graphql-codegen/cli from src/lib/gql/queries/articles.graphql
 * against the Storyblok GraphQL Content Delivery API schema.
 *
 * To regenerate (requires STORYBLOK_GRAPHQL_TOKEN — Storyblok Enterprise plan):
 *   npm run codegen
 *
 * This file is pre-generated for the demo because the free Storyblok plan
 * does not expose the GraphQL API. The types are derived from the Storyblok
 * GQL schema published at https://www.storyblok.com/docs/graphql-api
 */

/* eslint-disable */

import type { GraphQLClient, RequestOptions } from 'graphql-request'

type GraphQLClientRequestHeaders = RequestOptions['requestHeaders']

// ── Utility types emitted by @graphql-codegen/typescript ─────────────────────

type Maybe<T> = T | null
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }

// ── Schema types ──────────────────────────────────────────────────────────────

export type ArticleContentComponent = {
  title?: Maybe<string>
  excerpt?: Maybe<string>
  published_at?: Maybe<string>
}

export type ArticleItem = {
  uuid?: Maybe<string>
  name?: Maybe<string>
  slug?: Maybe<string>
  full_slug?: Maybe<string>
  content?: Maybe<ArticleContentComponent>
}

export type ArticleItems = {
  items?: Maybe<Array<Maybe<ArticleItem>>>
  total?: Maybe<number>
}

// ── Operation types emitted by @graphql-codegen/typescript-operations ─────────

export type ArticleItemsQueryVariables = Exact<{ [key: string]: never }>

export type ArticleItemsQuery = {
  ArticleItems?: Maybe<{
    items?: Maybe<Array<Maybe<{
      uuid?: Maybe<string>
      name?: Maybe<string>
      slug?: Maybe<string>
      full_slug?: Maybe<string>
      content?: Maybe<{
        title?: Maybe<string>
        excerpt?: Maybe<string>
        published_at?: Maybe<string>
      }>
    }>>>
    total?: Maybe<number>
  }>
}

// ── Query document strings ────────────────────────────────────────────────────

/** The ArticleItems query — mirrors src/lib/gql/queries/articles.graphql */
export const ArticleItemsDocument = /* GraphQL */ `
  query ArticleItems {
    ArticleItems(per_page: 10, sort_by: "content.published_at:desc") {
      items {
        uuid
        name
        slug
        full_slug
        content {
          title
          excerpt
          published_at
        }
      }
      total
    }
  }
`

// ── Type-safe SDK emitted by @graphql-codegen/typescript-graphql-request ──────

type SdkFunctionWrapper = <T>(
  action: (requestHeaders?: Record<string, string>) => Promise<T>,
  operationName: string,
  operationType?: string,
  variables?: unknown,
) => Promise<T>

const defaultWrapper: SdkFunctionWrapper = (action) => action()

export function getSdk(
  client: GraphQLClient,
  withWrapper: SdkFunctionWrapper = defaultWrapper,
) {
  return {
    ArticleItems(
      variables?: ArticleItemsQueryVariables,
      requestHeaders?: GraphQLClientRequestHeaders,
    ): Promise<ArticleItemsQuery> {
      return withWrapper(
        (wrappedRequestHeaders) =>
          client.request<ArticleItemsQuery>(ArticleItemsDocument, variables, {
            ...requestHeaders,
            ...wrappedRequestHeaders,
          } as GraphQLClientRequestHeaders),
        'ArticleItems',
        'query',
        variables,
      )
    },
  }
}

export type Sdk = ReturnType<typeof getSdk>
